# This is a basic workflow to help you get started with Actions

name: build_kernelsu_for_redbull_with_aosp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: "Release"
        required: true
        default: false
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Free Disk Space
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: ture

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      # Runs a single command using the runners shell
      - name: Preparing
        run: |
          cd ~/runner
          echo 'Preparing packages'
          sudo apt-get update -y
          sudo apt-get install -y repo git
          # echo 'cloning itself'
          # git clone https://github.com/Songkunda/kernelsu_pixel5
          mkdir android-kernel && cd android-kernel
          echo 'pulling kernel source'
          repo init -u https://android.googlesource.com/kernel/manifest -b android-msm-redbull-4.19-android13-qpr2
          repo sync

      - name: Build Kernel
        run: |
          cd ~/runner/android-kernel
          # ./build_redbull.sh
          ./build_redbull-gki.sh

      - name: Prepare AOSP
        run: |
          cd ~/runner
          mkdir aosp && cd aosp
          echo 'pulling aosp source'
          repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r43
          repo sync

      - name: prepare aosp driver
        run: |

          cd ~/runner/aosp
          DOWNLOAD_URL="https://dl.google.com/dl/android"
          echo 'pulling aosp drivers'
          curl --output - $DOWNLOAD_URL/aosp/qcom-redfin-tq2a.230505.002-f274a2f1.tgz | tar -xzvf -
          curl --output - $DOWNLOAD_URL/aosp/google_devices-redfin-tq2a.230505.002-3fdd0ec2.tgz | tar -xzvf -
          tail -n +315 extract-qcom-redfin.sh | tar -zxvf -
          tail -n +315 extract-google_devices-redfin.sh | tar -zxvf -

      - name: Build AOSP
        run: |
          cd ~/runner/aosp
          echo 'building AOSP'
          source build/envsetup.sh
          lunch aosp_redfin-userdebug
          echo "nproc: $(nproc --all)"
          make -j$(nproc --all)

      - name: zip AOSP
        run: |
          cd ~/runner/aosp/out/target/product/redfin/
          echo "-------打包文件记录-------"
          ls android-info.txt
          ls *.img
          echo "---------------------------"
          zip -r redfin-rom.zip *.txt *.img *.json

      - name: Upload kernel
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Image.lz4-dtb
          path: "~/runner/android-kernel/out/android-msm-pixel-4.19/dist/Image.lz4-dtb"

      - name: Upload AOSP
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: AOSP
          path: "~/runner/aosp/out/target/product/redfin/redfin-rom.zip"
